---
- name: Add fish repository from PPA and install its signing key on Ubuntu target.
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install the fish package.
  become: yes
  ansible.builtin.apt:
    name: fish
  update_cache: yes

- name: Ensure fish is added to /etc/shells.
  ansible.builtin.lineinfile:
    path: /etc/shells
    regexp: '^/bin/fish'
    line: /bin/fish
    owner: root
    group: root
    mode: '0644'
