---
- name: Create the user oryon.
  ansible.builtin.user:
    name: oryon
    comment: Oryon himself.
    password: $6$stjiFeKPhsWPjHnZ$rgaWCPBTx09ZwXMN5G2qDeUB6yac6bkKrOql6Rg9e.ElAmrSZGjl5Q19W4bWB/uEvq1J5wPrhpXQhN0SC78q/0
    state: present
    shell: /bin/fish
    groups: cyberise,wheel
    append: yes
    uid: 1337
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_comment: oryon@cyberise.de
    ssh_key_file: .ssh/id_ed25519_{{ lookup('env', 'NAME') | default('ANSIBLE', True) | upper }}
    ssh_key_type: ed25519
  register: user
