---
- name: Install common programs that don't need customization and are available via apt.
  become: true
  ansible.builtin.apt:
    pkg:  # TODO: inject items (plural) from variables
      - geany
    update_cache: yes


## 
# todo security packages for cutter, burp-suite-community ... etc

# TODO: fonts-powerline
