---
# tasks file for roles/surfacebook

# Only debian supported yet.
- name: Install Surfacebook Kernel from surface-linux for Debian.
  import_tasks: surfacebook2-debian.yml
  tags: surfacebook
  when: ansible_facts['os_family']|lower == "debian"


- name: Install Surfacebook Camera for Debian.
  include_tasks: camera.yml
  tags: surfacebook
  when: ansible_facts['os_family']|lower == "debian"


- name: Remove all dependencies that are no longer required for Debian.
  become: yes
  apt:
    autoremove: yes
  when: ansible_facts['os_family']|lower == "debian"

- name: Set a hostname for Debian.
  ansible.builtin.hostname:
    name: {{ hostname }}
    use: debian
